sources:

  unit42:
    enabled: true
    type: rss

    feed_url: https://unit42.paloaltonetworks.com/feed/

    name: Unit42
    hashtag: unit42

    categories:
      - Threat Research
      - High Profile Threats
      - Threat Actor Groups


  tenable:
    enabled: true
    type: rss

    feed_url: https://www.tenable.com/blog/cyber-exposure-alerts/feed

    name: Tenable
    hashtag: tenable

  certua:
    enabled: true
    type: rss

    feed_url: https://cert.gov.ua/api/articles/rss

    name: CERT-UA
    hashtag: certua

  sekoia:
      enabled: true
      type: html

      name: Sekoia
      hashtag: sekoia

      category: Threat Research & Intelligence

  hunt:
      enabled: true
      type: html

      feed_url: https://hunt.io/blog

      name: Hunt.io
      hashtag: huntio

      victim_regions: 
        - "EU"
        - "Global"
        - "Middle East"
      category: Threat Research
      start_date: "2026-06-01"


telegram:
  enabled: true
  parse_mode: HTML
